### ISSUE TITLE
Race Condition in Event Handler Processing

### ISSUE THREAD

**Issue by mshakeg** [sentioxyz/sentio-sdk#1102]
### Description

The Sentio processor runtime appears to be executing event handlers concurrently instead of sequentially, leading to race conditions when processing events from the same transaction. This causes data consistency issues when later events depend on state changes from earlier events.

### Reproduction

1. Clone the example processor repository:
```bash
git clone https://github.com/Canopyxyz/sentio-processors
cd sentio-processors
```

2. Install dependencies and build:
```bash
pnpm install
pnpm gen
pnpm build
```

3. Upload the processor:
```bash
pnpm upload
```

The issue can be observed in the multi-rewards processor implementation, specifically in the interaction between `StakeEvent` and `SubscriptionEvent` handlers.

### Datasource Logs on the Sentio Dashboard Showing the Issue

```
Jan 09 16:20:21.027: In StakeEvent 1
Jan 09 16:20:21.027: In StakeEvent 2
Jan 09 16:20:21.029: In SubscriptionEvent
Jan 09 16:20:21.035: In StakeEvent 3
Jan 09 16:20:21.070: SubscriptionEvent: timestamp: 1730486529129000; userAddress: 0xbee7f0e5192c31d6fd4c90c83d567230ee23cbc2f10138a89c231e40c05bee13: staking_token: 0xdaf28c5ba0736813bdd1a6d225ce787ee9f4ed22c3bfc660297a4e2a343d620b; userStakedBalance: false
Jan 09 16:20:21.176: process error 4 {"code":13,"details":"error processing event: // rest of this log omitted for brevity...
Jan 09 16:20:21.179: In StakeEvent 4
```

### Expected Behavior

Event handlers from the same transaction and for the same processor should be processed sequentially to maintain data consistency. In this case, the `StakeEvent` handler should complete its execution (including creating the user's staked balance) before the `SubscriptionEvent` handler begins processing.

### Actual Behavior

The logs show that the `SubscriptionEvent` handler begins execution (at 16:20:21.029) before the `StakeEvent` handler completes. This causes the `SubscriptionEvent` handler to fail because it cannot find the user's staked balance, which should have been created by the `StakeEvent` handler.

### Impact

This race condition causes processing failures when events have implicit ordering dependencies. In our case:
1. `StakeEvent` creates a user's staked balance
2. `SubscriptionEvent` requires this staked balance to exist
3. Concurrent processing causes the `SubscriptionEvent` to fail because it runs before the staked balance is created

### Additional Context

The full processor implementation can be found in the **canopyxyz/sentio-processors** repo, specifically in the multi-rewards processor implementation.

### Possible Solutions

1. Ensure event handlers are processed sequentially when events are from the same transaction
2. Implement a transaction-level lock mechanism in the runtime
3. Add explicit ordering constraints for event processing

### Workaround

While waiting for a fix, we can implement a global sequential lock mechanism to ensure strict ordering of all event processing. Here's a possible implementation:

```typescript
// Global sequential lock for event processing
class EventProcessingLock {
  private currentOperation: Promise<void> = Promise.resolve();

  async withLock<T>(operation: () => Promise<T>): Promise<T> {
    const execute = async (): Promise<T> => {
      try {
        return await operation();
      } catch (error) {
        console.error('Event processing error:', error);
        throw error; // Re-throw to ensure proper error handling
      }
    };

    // Queue this operation behind any existing ones
    const result = this.currentOperation.then(execute);
    
    // Update the current operation, ensuring cleanup happens
    this.currentOperation = result.then(
      () => {}, // Success case
      () => {}  // Error case - ensure chain continues even after error
    );

    return result;
  }
}

// Create a single instance of the sequential lock
const eventLock = new EventProcessingLock();

// Modify the processor to use the sequential lock
export function multiRewardsProcessor(
  supportedChainId: SupportedAptosChainId,
  startVersion: number,
  baseProcessor: MultiRewardsProcessor,
) {
  baseProcessor
    .bind({ startVersion })
    .onEventStakeEvent(async (event, ctx) => {
      return eventLock.withLock(async () => {
        // Existing stake event logic
        const store = getStore(supportedChainId, ctx);
        const timestampMicros = ctx.getTimestamp();
        // ... rest of the stake event logic
      });
    })
    .onEventSubscriptionEvent(async (event, ctx) => {
      return eventLock.withLock(async () => {
        // Existing subscription event logic
        const store = getStore(supportedChainId, ctx);
        const timestampMicros = ctx.getTimestamp();
        // ... rest of the subscription event logic
      });
    })
    // Apply to all other event handlers...
}
```

This workaround ensures:

1. Strict sequential processing of ALL events, maintaining proper ordering regardless of user or event type
2. No concurrent event processing can occur
3. Error handling that won't block subsequent events
4. Simple, deterministic behavior that matches the expected runtime execution model

Key advantages over a user-level lock:
- Preserves global state consistency
- Prevents race conditions between different users' events
- Maintains proper ordering of system-level state changes
- Simpler to reason about and debug

While this workaround should resolve the immediate issue, it's important to note that this shouldn't be necessary as the runtime should handle sequential processing automatically.

**Comment by mshakeg** [comment]
After implementing the `EventProcessingLock` workaround in the [dev branch](https://github.com/Canopyxyz/sentio-processors/tree/dev), I've discovered a more fundamental issue with event processing in the Sentio runtime.

The runtime appears to be initiating event handler calls out of order relative to their original transaction sequence. This happens before our sequential processing lock can help.

Example from testnet transaction [0x19d0910aa132ccfbd750494e8e579f1cc4df6d4e23c5315925acfdef2896c3f2](https://explorer.aptoslabs.com/txn/0x19d0910aa132ccfbd750494e8e579f1cc4df6d4e23c5315925acfdef2896c3f2/events?network=testnet):

Original transaction order:
1. `StakeEvent`
2. `SubscriptionEvent`

However, Sentio runtime processing logs show in chronological order:

```
Jan 10 18:47:43.838: In SubscriptionEvent: 0x19d0910aa132ccfbd750494e8e579f1cc4df6d4e23c5315925acfdef2896c3f2
Jan 10 18:47:43.848: SubscriptionEvent: timestamp: 1731605611129000; userAddress: 0xd7c1ae941e87e28b621da69bb56fd0c296ffd76511b770b3501cd7b61b9aa485: staking_token: 0xdaf28c5ba0736813bdd1a6d225ce787ee9f4ed22c3bfc660297a4e2a343d620b; userStakedBalance: false
Jan 10 18:47:43.848: In StakeEvent: 0x19d0910aa132ccfbd750494e8e579f1cc4df6d4e23c5315925acfdef2896c3f2
```

The `SubscriptionEvent` handler is called before the `StakeEvent` handler, despite occurring later in the transaction. This causes the `SubscriptionEvent` to fail because it depends on state (userStakedBalance) that should have been created by the `StakeEvent`.

While our `EventProcessingLock` ensures sequential execution once handlers are called, it cannot fix incorrect event ordering at the runtime level. The runtime needs to preserve the original transaction's event sequence to maintain data consistency.

**Comment by mshakeg** [comment]
Hey @spacedragon @rnons @zfy0701 would really appreciate if y'all could look into especially this issue, but also some of the other issues I've recently created. I'm developing processors for **Canopyxyz**(a dApp on Movement) that we plan to use over rpc view calls, and these seem like serious bugs in the sentio runtime and are major blockers to our processors functioning.

**Comment by zfy0701** [comment]
@spacedragon is looking at this

**Comment by zfy0701** [comment]
in your case, does two event in same block or different block? 

have you try this first?

https://github.com/sentioxyz/sentio-processors/blob/fcd791c052599acfc9d46dd28db9434bc8d12c4f/points/rho/stakestone-scroll-rho-points/src/processor.ts#L21

this would gurantee executation order

**Comment by mshakeg** [comment]
@zfy0701 if you look at the events in the tx linked in [this comment](https://github.com/sentioxyz/sentio-sdk/issues/1102#issuecomment-2582936252) you'll see that the `StakeEvent` and the `SubscriptionEvent` are emitted in the same transaction.

Also, I tried your suggested change, and it didn't fix the issue:

https://github.com/Canopyxyz/sentio-processors/tree/dev

**Comment by zfy0701** [comment]
got it, will get it fixed tomorrow

**Comment by zfy0701** [comment]
sorry for the delay @mshakeg but it should be fixed
also read more here about execution order
https://docs.sentio.xyz/docs/execution-order-and-processor-state#/

**Comment by zfy0701** [comment]
could u also upgrade sdk version to 2.55.2?

**Comment by mshakeg** [comment]
@zfy0701 I did, however I'm now getting a type error on the sentio generated types, see here:

https://github.com/Canopyxyz/sentio-processors/pull/2

**Comment by zfy0701** [comment]
hi, there is lots of indirect dependencies you need to update, however, I would suggest use shameless hoist to simplify this

also since there seems something else been changed, I just sent your a PR

https://github.com/Canopyxyz/sentio-processors/pull/3/files

**Comment by mshakeg** [comment]
Hey @zfy0701 I just uploaded the version on your branch and it's still the same issue. The `SubscriptionEvent` handler begins execution before the `StakeEvent` handler has fully completed execution, and so it fails since the `SubscriptionEvent` handler expects state that the `StakeEvent` creates.

<img width="1236" alt="Image" src="https://github.com/user-attachments/assets/e7f53445-13f5-4012-8559-fd1a64359830" />

**Comment by zfy0701** [comment]
@mshakeg sequential mode should also be enabled for now, could you try that

**Comment by zfy0701** [comment]
we'll make the default behavior exact as we describe in the doc, parallel between blocks, sequential within block, but with that I suspect in your case you still need sequential mode. close this since we have other issue track this internally now
